---
- name: Deploy Angular Application
  hosts: web
  become: yes
  vars:
    version: "{{ version }}"
    artifact_path: "{{ artifact_path }}"
  roles:
  - apache
  - deploy
- name: Configure MariaDB (Optional)
  hosts: db
  become: yes
  vars:
    db_name: angular_db
    db_user: angular_user
    db_password: secure_password_here # Use Ansible Vault in real projects
  roles:
  - mariadb
- name: Rollback Angular App
  hosts: web
  become: yes
  vars:
    version: "rollback"
    artifact_path: "rollback"
  tasks:
  - import_tasks: roles/deploy/tasks/rollback.yml
  when: rollback | default(false)
- name: Deploy Angular App (Install + Deploy)
  hosts: web
  become: yes
  vars:
    version: "{{ version }}"
    artifact_path: "{{ artifact_path }}"
  roles:
  - deploy
  when: not rollback | default(false)
