---
# tasks file for roles/mariadb
- name: Install Apache2
  apt:
    name: apache2
    update_cache: yes
    state: present
- name: Start and enable Apache2
  service:
    name: apache2
    state: started
    enabled: yes
