---
- name: Create version-specific directory
  file:
    path: "{{ versions_path }}/{{ app_version }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Extract Angular application to version directory
  unarchive:
    src: "{{ app_name }}-{{ app_version }}.tar.gz"
    dest: "{{ versions_path }}/{{ app_version }}"
    remote_src: "{{ not rollback | bool }}"  # Use remote_src=false if deploying from Jenkins artifact
    owner: www-data
    group: www-data

- name: Update current version symlink
  file:
    src: "{{ versions_path }}/{{ app_version }}"
    dest: "{{ deploy_path }}"
    state: link
    force: yes
    owner: www-data
    group: www-data

- name: Create version info file
  copy:
    content: "{{ app_version }}"
    dest: "{{ versions_path }}/current-version.txt"
    owner: www-data
    group: www-data
